# Generated by Django 5.1 on 2024-10-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_task_recurrence_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
